---

grafana_external_url: stats.superkooka.com
grafana_host_url: 127.0.0.1
grafana_host_port: 3000

miniflux_admin_username: superkooka
miniflux_external_url: rss.superkooka.com
miniflux_host_url: 127.0.0.1
miniflux_host_port: 3001

caddy_lets_encrypt_email: aymeric.gueracague@gmail.com
caddy_sites:
  - domain: "{{ miniflux_external_url }}"
    proxy_pass: "http://{{ miniflux_host_url }}:{{ miniflux_host_port }}"

  - domain: "{{ grafana_external_url }}"
    proxy_pass: "http://{{ grafana_host_url }}:{{ grafana_host_port }}"
