---
manager:
  include_meta: False
  max_workers: 2

providers:
  zones:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    default_ttl: 3600
    enforce_order: True
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    email: env/CLOUDFLARE_EMAIL
    token: env/CLOUDFLARE_TOKEN
  bind9:
      class: octodns_bind.Rfc2136Provider
      host: ns1.superkooka.com
      key_name: env/AXFR_KEY_NAME
      key_secret: env/AXFR_KEY_SECRET
      key_algorithm: hmac-sha256

zones:
  superkooka.com.:
    sources:
      - zones
    targets:
      - cloudflare
  superkooka.home.:
    sources:
      - zones
    targets:
      - bind9