---
- name: Install required packages by Docker
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
    state: present

- name: Add Docker Apt signing key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /usr/share/keyrings/docker.asc

- name: Add Docker Apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/docker.asc] https://download.docker.com/linux/debian bullseye stable"
    state: present
    filename: docker

- name: Install docker
  ansible.builtin.apt:
    pkg: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      # - docker-buildx-plugin
      # - docker-compose-plugin
    state: present
    update_cache: yes

- name: Install Docker SDK
  ansible.builtin.pip:
    name: docker
    state: present
    virtualenv: "{{ docker_venv }}"

- name: Create a application network
  community.docker.docker_network:
    name: raspi
  vars:
    ansible_python_interpreter: "{{ docker_venv }}/bin/python"
