---
- name: Provision basic raspi debian image
  hosts: rasp
  become: true
  gather_facts: no
  tasks:
    - name: Installer Python
      raw: apt update && apt install -y python3 python3-setuptools python3-wheel python3-virtualenv
