---
- name: "Open http{1,2,3} port"
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: "80", proto: tcp }  # http1
    - { port: "443", proto: tcp } # http2
    - { port: "443", proto: udp } # http3

- name: Add caddy group
  ansible.builtin.group:
    name: caddy
    system: yes
    state: present

- name: Add caddy user
  ansible.builtin.user:
    name: caddy
    system: yes
    home: /var/lib/caddy
    shell: /usr/sbin/nologin
    group: caddy

- name: Add Caddy Apt signing key
  ansible.builtin.get_url:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    dest: /usr/share/keyrings/caddy-stable.asc

- name: Add Caddy Apt repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    filename: caddy-stable
  with_items:
    - "deb [signed-by=/usr/share/keyrings/caddy-stable.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    - "deb-src [signed-by=/usr/share/keyrings/caddy-stable.asc] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    update_cache: yes
    state: present

- name: Enable Caddy on system boot
  ansible.builtin.systemd:
    name: caddy.service
    enabled: yes
    daemon_reload: yes

- name: Configure caddy
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: caddy
    group: caddy
  notify:
    - restart-caddy
