---
name: Ansible Lint

on:
  push:
    paths:
      - ansible/**
      - .github/workflows/ansible-lint.yml
  pull_request:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Ansible
      run: python -m pip install ansible ansible-lint
    - name: Lint ansible folder
      run: |
        cd ansible
        ansible-lint -p deploy_rasp.yaml